// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.fr');

goog.require('Blockly.Msg');

Blockly.Msg.ARD_ANALOGREAD = "Lecture du signal analogique #";
Blockly.Msg.ARD_ANALOGREAD_TIP = "Valeur de retour entre 0 et 1024";
Blockly.Msg.ARD_ANALOGWRITE = "Ecriture du signal analogique #";
Blockly.Msg.ARD_ANALOGWRITE_TIP = "Ecrit une valeur analogique comprise entre 0 et 255 sur un port PWM spécifique";
Blockly.Msg.ARD_BUILTIN_LED = "Configurer la DEL";
Blockly.Msg.ARD_BUILTIN_LED_TIP = "Allumer ou éteindre la DEL de la carte";
Blockly.Msg.ARD_COMPONENT_WARN1 = "A %1 configuration block with the same %2 name must be added to use this block!";  // untranslated
Blockly.Msg.ARD_DEFINE = "Définir";
Blockly.Msg.ARD_DIGITALREAD = "Lecture du signal numérique #";
Blockly.Msg.ARD_DIGITALREAD_TIP = "Lecture de la valeur d'un signal numérique: HAUT ou BAS";
Blockly.Msg.ARD_DIGITALWRITE = "Configuration du signal numérique #";
Blockly.Msg.ARD_DIGITALWRITE_TIP = " Ecriture de la valeur HAUT ou BAS du signal numérique #";
Blockly.Msg.ARD_FUN_RUN_LOOP = "Arduino boucle infinie:";
Blockly.Msg.ARD_FUN_RUN_SETUP = "Arduino exécute en premier:";
Blockly.Msg.ARD_FUN_RUN_TIP = "Definition de la configuration de l'Arduino: fonctions setup() et loop().";
Blockly.Msg.ARD_HIGH = "HAUT";
Blockly.Msg.ARD_HIGHLOW_TIP = " Configuration d'un signal à l'état HAUT ou BAS";
Blockly.Msg.ARD_LCD_AT = "en";
Blockly.Msg.ARD_LCD_COLS = "Nombre de colonnes";
Blockly.Msg.ARD_LCD_DATACOUNT = "Nombre de données";
Blockly.Msg.ARD_LCD_HASRW = "signal RW connecté ?";
Blockly.Msg.ARD_LCD_PRINT = "Afficher";
Blockly.Msg.ARD_LCD_PRINT_HINT = "Permet d'afficher un message sur l'écran LCD de l'arduino";
Blockly.Msg.ARD_LCD_PRINT_NOINST = "Un bloc de configuration d'écran LCD doit être ajouté afin d'utiliser ce bloc!";
Blockly.Msg.ARD_LCD_ROWS = "Nombre de lignes";
Blockly.Msg.ARD_LCD_SETUP = "Configurer LCD";
Blockly.Msg.ARD_LCD_SETUP_HINT = "Permet de configurer l'écran LCD de l'arduino";
Blockly.Msg.ARD_LOW = "BAS";
Blockly.Msg.ARD_MAP = "Converti";
Blockly.Msg.ARD_MAP_TIP = "Converti un nombre de la plage [0-1024].";
Blockly.Msg.ARD_MAP_VAL = "valeur de [0-";
Blockly.Msg.ARD_NOTONE = "Eteindre la tonalité du signal #";
Blockly.Msg.ARD_NOTONE_PIN = "PAS de Signal de tonalité #";
Blockly.Msg.ARD_NOTONE_PIN_TIP = "Arret de la génération de tonalité (son)sur un signal";
Blockly.Msg.ARD_NOTONE_TIP = "Eteindre / Activer la tonalité du signal selectioné";
Blockly.Msg.ARD_PIN_WARN1 = "Signal %1 est utilisé pour %2 alors que signal %3. Déjà utilisé en tant que %4.";
Blockly.Msg.ARD_PULSETIMEOUT_TIP = "Mesure la durée d'une pulsation sur le signal selectioné, dans le delai imparti";
Blockly.Msg.ARD_PULSE_READ = "mesure %1 impulsion sur le signal #%2";
Blockly.Msg.ARD_PULSE_READ_TIMEOUT = "mesure %1 impulsion sur le signal #%2 (délai de retard %3 μs)";
Blockly.Msg.ARD_PULSE_TIP = "Mesure la durée d'une pulsation sur le signal selectioné.";
Blockly.Msg.ARD_SERIAL_BPS = "bps";
Blockly.Msg.ARD_SERIAL_PRINT = "imprimer";
Blockly.Msg.ARD_SERIAL_PRINT_NEWLINE = "ajouter une nouvelle ligne";
Blockly.Msg.ARD_SERIAL_PRINT_TIP = "Imprime les données sur la console série en texte lisible ASCII.";
Blockly.Msg.ARD_SERIAL_PRINT_WARN = "Un bloc de configuration pour %1 doit être ajouté à l'espace de travail afin d'utiliser ce bloc!";
Blockly.Msg.ARD_SERIAL_SETUP = "Configuration";
Blockly.Msg.ARD_SERIAL_SETUP_TIP = "Choisir la vitesse d'un périphérique série";
Blockly.Msg.ARD_SERIAL_SPEED = ":  vitesse";
Blockly.Msg.ARD_SERVO_READ = "Lecture du signal# du SERVO";
Blockly.Msg.ARD_SERVO_READ_TIP = "Lecture d'un angle du SERVO";
Blockly.Msg.ARD_SERVO_WRITE = "Configurer SERVO sur Patte";
Blockly.Msg.ARD_SERVO_WRITE_DEG_180 = "Degrés (0~180)";
Blockly.Msg.ARD_SERVO_WRITE_TIP = "Configurer un SERVO à un angle donné";
Blockly.Msg.ARD_SERVO_WRITE_TO = "vers";
Blockly.Msg.ARD_SETTONE = "Définir une tonalité sur le signal #";
Blockly.Msg.ARD_SPI_SETUP = "Configuration";
Blockly.Msg.ARD_SPI_SETUP_CONF = "configuration:";
Blockly.Msg.ARD_SPI_SETUP_DIVIDE = "Division de fréquence";
Blockly.Msg.ARD_SPI_SETUP_LSBFIRST = "LSBFIRST";
Blockly.Msg.ARD_SPI_SETUP_MODE = "mode SPI  (idle - edge)";
Blockly.Msg.ARD_SPI_SETUP_MODE0 = "0 (Bas - Descendant)";
Blockly.Msg.ARD_SPI_SETUP_MODE1 = "1 (Bas - Montant)";
Blockly.Msg.ARD_SPI_SETUP_MODE2 = "2 (Haut - Descendant)";
Blockly.Msg.ARD_SPI_SETUP_MODE3 = "3 (Haut - Montant)";
Blockly.Msg.ARD_SPI_SETUP_MSBFIRST = "MSBFIRST";
Blockly.Msg.ARD_SPI_SETUP_SHIFT = "décalage de données";
Blockly.Msg.ARD_SPI_SETUP_TIP = "Configuration du périphérique SPI.";
Blockly.Msg.ARD_SPI_TRANSRETURN_TIP = "Envoie d'un message SPI à un esclave précis et recuperation de la donnée.";
Blockly.Msg.ARD_SPI_TRANS_NONE = "vide";
Blockly.Msg.ARD_SPI_TRANS_SLAVE = "vers le signal esclave";
Blockly.Msg.ARD_SPI_TRANS_TIP = "Envoie d'un message SPI à un esclave précis.";
Blockly.Msg.ARD_SPI_TRANS_VAL = "transfert";
Blockly.Msg.ARD_SPI_TRANS_WARN1 = "Un bloc de configuration pour %1 doit être ajouté à l'espace de travail afin d'utiliser ce bloc!";
Blockly.Msg.ARD_SPI_TRANS_WARN2 = "L'ancienne valeur du signal %1 n'est plus disponible.";
Blockly.Msg.ARD_STEPPER_COMPONENT = "stepper";  // untranslated
Blockly.Msg.ARD_STEPPER_DEFAULT_NAME = "MyStepper";  // untranslated
Blockly.Msg.ARD_STEPPER_FOUR_PINS = "4";
Blockly.Msg.ARD_STEPPER_MOTOR = "Moteur pas-à-pas:";
Blockly.Msg.ARD_STEPPER_NUMBER_OF_PINS = "Number of pins";  // untranslated
Blockly.Msg.ARD_STEPPER_PIN1 = "signal1 #";
Blockly.Msg.ARD_STEPPER_PIN2 = "signal2 #";
Blockly.Msg.ARD_STEPPER_PIN3 = "signal3 #";
Blockly.Msg.ARD_STEPPER_PIN4 = "signal4 #";
Blockly.Msg.ARD_STEPPER_REVOLVS = "Combien de pas par tour";
Blockly.Msg.ARD_STEPPER_SETUP = "Configuration";
Blockly.Msg.ARD_STEPPER_SETUP_TIP = "Configuration d'un moteur pas-à-pas: signaux et autres paramètres.";
Blockly.Msg.ARD_STEPPER_SPEED = "Configuration de la vitesse(rpm) à";
Blockly.Msg.ARD_STEPPER_STEP = "Déplacement grace au moteur pas-à-pas";
Blockly.Msg.ARD_STEPPER_STEPS = "pas";
Blockly.Msg.ARD_STEPPER_STEP_TIP = "Configurer le moteur pas-à-pas avec un nombre précis de pas.";
Blockly.Msg.ARD_STEPPER_TWO_PINS = "2";
Blockly.Msg.ARD_TIME_DELAY = "Délai d'attente de";
Blockly.Msg.ARD_TIME_DELAY_MICROS = "microsecondes";
Blockly.Msg.ARD_TIME_DELAY_MICRO_TIP = "Attendre un délai précis en microsecondes";
Blockly.Msg.ARD_TIME_DELAY_TIP = "Attendre un délai précis en millisecondes";
Blockly.Msg.ARD_TIME_INF = "Attente sans fin (fin du programme)";
Blockly.Msg.ARD_TIME_INF_TIP = "Attente indéfinie, arrêt du programme.";
Blockly.Msg.ARD_TIME_MICROS = "Temps écoulé (microsecondes)";
Blockly.Msg.ARD_TIME_MICROS_TIP = "Renvoie le temps en microseconds depuis le lancement de ce programme sur la carte Arduino. Doit être stocké dans un Entier long positif";
Blockly.Msg.ARD_TIME_MILLIS = "Temps écoulé (millisecondes)";
Blockly.Msg.ARD_TIME_MILLIS_TIP = "Renvoie le temps en milliseconds depuis le lancement de ce programme sur la carte Arduino. Doit être stocké dans un Entier long positif";
Blockly.Msg.ARD_TIME_MS = "millisecondes";
Blockly.Msg.ARD_TONEFREQ = "à la frequence";
Blockly.Msg.ARD_TONE_FREQ = "frequence";
Blockly.Msg.ARD_TONE_PIN = "Signal de tonalité #";
Blockly.Msg.ARD_TONE_PIN_TIP = "Génération de tonalité (son)sur un signal";
Blockly.Msg.ARD_TONE_TIP = " Configurer le signal de tonalité dans la plage: 31 - 65535";
Blockly.Msg.ARD_TONE_WARNING = "La fréquence doit être dans la plage 31 - 65535";
Blockly.Msg.ARD_TYPE_ARRAY = "Tableau";
Blockly.Msg.ARD_TYPE_BOOL = "Booléen";
Blockly.Msg.ARD_TYPE_CHAR = "Charactère";
Blockly.Msg.ARD_TYPE_CHILDBLOCKMISSING = "Dépendance manquante";
Blockly.Msg.ARD_TYPE_DECIMAL = "Décimal";
Blockly.Msg.ARD_TYPE_LONG = "Entier long";
Blockly.Msg.ARD_TYPE_NULL = "Null";
Blockly.Msg.ARD_TYPE_NUMBER = "Entier";
Blockly.Msg.ARD_TYPE_SHORT = "Entier court";
Blockly.Msg.ARD_TYPE_TEXT = "Texte";
Blockly.Msg.ARD_TYPE_UNDEF = "Non défini";
Blockly.Msg.ARD_VAR_AS = "comme";
Blockly.Msg.ARD_VAR_AS_TIP = "Configure une valeur à un type précis";
Blockly.Msg.ARD_WRITE_TO = "à";
Blockly.Msg.NEW_INSTANCE = "New instance...";  // untranslated
Blockly.Msg.NEW_INSTANCE_TITLE = "New instance name:";  // untranslated
Blockly.Msg.RENAME_INSTANCE = "Rename instance...";  // untranslated
Blockly.Msg.RENAME_INSTANCE_TITLE = "Rename all '%1' instances to:";  // untranslated
