// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.it');

goog.require('Blockly.Msg');

Blockly.Msg.ARD_ANALOGREAD = "leggi pin analogico #";
Blockly.Msg.ARD_ANALOGREAD_TIP = "Ritorna un valore tra 0 e 1024";
Blockly.Msg.ARD_ANALOGWRITE = "imposta il pin analogico #";
Blockly.Msg.ARD_ANALOGWRITE_TIP = "Scrivi un valore analogico fra 0 e 255 su una Porta PWM specifica";
Blockly.Msg.ARD_BUILTIN_LED = "imposta il LED on-board";
Blockly.Msg.ARD_BUILTIN_LED_TIP = "Accendi o spegni il LED on-board di Arduino";
Blockly.Msg.ARD_COMPONENT_WARN1 = "Un blocco di configurazione %1 con lo stesso nome %2 va aggiunto a questo blocco!";
Blockly.Msg.ARD_DEFINE = "Definisci";
Blockly.Msg.ARD_DIGITALREAD = "leggi il pin digitale #";
Blockly.Msg.ARD_DIGITALREAD_TIP = "Leggi il valore digitale su un pin: ALTO o BASSO";
Blockly.Msg.ARD_DIGITALWRITE = "imposta il pin digitale #";
Blockly.Msg.ARD_DIGITALWRITE_TIP = "Scrivi un valore digitale ALTO o BASSO su una Porta specifica";
Blockly.Msg.ARD_FUN_RUN_LOOP = "Loop Arduino:";
Blockly.Msg.ARD_FUN_RUN_SETUP = "Setup Arduino:";
Blockly.Msg.ARD_FUN_RUN_TIP = "Definisce le funzioni setup() e loop() di Arduino.";
Blockly.Msg.ARD_HIGH = "ALTO";
Blockly.Msg.ARD_HIGHLOW_TIP = "Imposta lo stato logico del pin a Alto o Basso.";
Blockly.Msg.ARD_LCD_AT = "at";  // untranslated
Blockly.Msg.ARD_LCD_COLS = "Number of columns";  // untranslated
Blockly.Msg.ARD_LCD_DATACOUNT = "Number of data";  // untranslated
Blockly.Msg.ARD_LCD_HASRW = "RW signal connected ?";  // untranslated
Blockly.Msg.ARD_LCD_PRINT = "Display";  // untranslated
Blockly.Msg.ARD_LCD_PRINT_HINT = "Print a message on the LCD display of the arduino";  // untranslated
Blockly.Msg.ARD_LCD_PRINT_NOINST = "A configuration bloc for LCD display must be added to use this block!";  // untranslated
Blockly.Msg.ARD_LCD_ROWS = "Number of rows";  // untranslated
Blockly.Msg.ARD_LCD_SETUP = "Setup LCD";  // untranslated
Blockly.Msg.ARD_LCD_SETUP_HINT = "Setup the LCD display from arduino starter kit";  // untranslated
Blockly.Msg.ARD_LOW = "BASSO";
Blockly.Msg.ARD_MAP = "Mappa";
Blockly.Msg.ARD_MAP_TIP = "Mappa un numero nell'intervallo [0-1024] a un'altro numero.";
Blockly.Msg.ARD_MAP_VAL = "valore a [0-";
Blockly.Msg.ARD_NOTONE = "Spegne il tono sul pin #";
Blockly.Msg.ARD_NOTONE_PIN = "Nessun tono sul PIN#";
Blockly.Msg.ARD_NOTONE_PIN_TIP = "Ferma la generazione di un tono su un pin.";
Blockly.Msg.ARD_NOTONE_TIP = "Spegne il tono sul pin selezionato";
Blockly.Msg.ARD_PIN_WARN1 = "Il Pin %1 è richiesto dal %2 come pin %3. Già usato come %4.";
Blockly.Msg.ARD_PULSETIMEOUT_TIP = "Misura la durata di un impulso sul pin selezionato, se è compreso all'interno del timeout.";
Blockly.Msg.ARD_PULSE_READ = "misura %1 impulso sul pin #%2";
Blockly.Msg.ARD_PULSE_READ_TIMEOUT = "misura %1 impulso sul pin #%2 (timeout dopo %3 μs)";
Blockly.Msg.ARD_PULSE_TIP = "Misura la durata di un impulso sul pin selezionato.";
Blockly.Msg.ARD_SERIAL_BPS = "bps";
Blockly.Msg.ARD_SERIAL_PRINT = "stampa";
Blockly.Msg.ARD_SERIAL_PRINT_NEWLINE = "aggiungi una nuova riga";
Blockly.Msg.ARD_SERIAL_PRINT_TIP = "Stampa dei dati sulla console/porta seriale in un formato leggibile (ASCII).";
Blockly.Msg.ARD_SERIAL_PRINT_WARN = "Per utilizzare questo blocco devi aggiungere un blocco di setup per %1 nell'area di lavoro!";
Blockly.Msg.ARD_SERIAL_SETUP = "Imposta";
Blockly.Msg.ARD_SERIAL_SETUP_TIP = "Seleziona la velocità di una periferica Seriale";
Blockly.Msg.ARD_SERIAL_SPEED = ": velocità a";
Blockly.Msg.ARD_SERVO_READ = "leggi SERVO dal Pin#";
Blockly.Msg.ARD_SERVO_READ_TIP = "Leggi l'angolazione di un Servo motore";
Blockly.Msg.ARD_SERVO_WRITE = "configura un SERVO sul Pin";
Blockly.Msg.ARD_SERVO_WRITE_DEG_180 = "(0~180) gradi";
Blockly.Msg.ARD_SERVO_WRITE_TIP = "Imposta un Servo all'angolazione specificata";
Blockly.Msg.ARD_SERVO_WRITE_TO = "a";
Blockly.Msg.ARD_SETTONE = "Imposta un tono sul pin #";
Blockly.Msg.ARD_SPI_SETUP = "Imposta";
Blockly.Msg.ARD_SPI_SETUP_CONF = "configurazione:";
Blockly.Msg.ARD_SPI_SETUP_DIVIDE = "divisione di frequenza";
Blockly.Msg.ARD_SPI_SETUP_LSBFIRST = "LSBFIRST";
Blockly.Msg.ARD_SPI_SETUP_MODE = "modalità SPI (idle - edge)";
Blockly.Msg.ARD_SPI_SETUP_MODE0 = "0 (Basso - Discendente)";
Blockly.Msg.ARD_SPI_SETUP_MODE1 = "1 (Basso - Ascendente)";
Blockly.Msg.ARD_SPI_SETUP_MODE2 = "2 (Alto - Discendente)";
Blockly.Msg.ARD_SPI_SETUP_MODE3 = "3 (Alto - Ascendente)";
Blockly.Msg.ARD_SPI_SETUP_MSBFIRST = "MSBFIRST";
Blockly.Msg.ARD_SPI_SETUP_SHIFT = "dati di correzione";
Blockly.Msg.ARD_SPI_SETUP_TIP = "Configura la periferica SPI.";
Blockly.Msg.ARD_SPI_TRANSRETURN_TIP = "Invia un messaggio SPI al dispositivo slave specificato e ricevi indietro dei dati.";
Blockly.Msg.ARD_SPI_TRANS_NONE = "vuoto";
Blockly.Msg.ARD_SPI_TRANS_SLAVE = "al pin slave";
Blockly.Msg.ARD_SPI_TRANS_TIP = "Invia un messaggio SPI al dispositivo slave specificato.";
Blockly.Msg.ARD_SPI_TRANS_VAL = "trasferimento";
Blockly.Msg.ARD_SPI_TRANS_WARN1 = "Per utilizzare questo blocco devi aggiungere un blocco di setup per %1 nell'area di lavoro!";
Blockly.Msg.ARD_SPI_TRANS_WARN2 = "Il precedente valore del pin %1 non è più disponibile.";
Blockly.Msg.ARD_STEPPER_COMPONENT = "stepper";
Blockly.Msg.ARD_STEPPER_DEFAULT_NAME = "MyStepper";
Blockly.Msg.ARD_STEPPER_FOUR_PINS = "4";
Blockly.Msg.ARD_STEPPER_MOTOR = "motore stepper:";
Blockly.Msg.ARD_STEPPER_NUMBER_OF_PINS = "Numero di pin";
Blockly.Msg.ARD_STEPPER_PIN1 = "pin1#";
Blockly.Msg.ARD_STEPPER_PIN2 = "pin2#";
Blockly.Msg.ARD_STEPPER_PIN3 = "pin3#";
Blockly.Msg.ARD_STEPPER_PIN4 = "pin4#";
Blockly.Msg.ARD_STEPPER_REVOLVS = "quanti passi per ogni rotazione";
Blockly.Msg.ARD_STEPPER_SETUP = "Imposta un motore stepper";
Blockly.Msg.ARD_STEPPER_SETUP_TIP = "Configura i pin e altre impostazioni di un motore stepper.";
Blockly.Msg.ARD_STEPPER_SPEED = "imposta la velocità (rpm) a";
Blockly.Msg.ARD_STEPPER_STEP = "muovi stepper";
Blockly.Msg.ARD_STEPPER_STEPS = "passi";
Blockly.Msg.ARD_STEPPER_STEP_TIP = "Fai girare di un certo numero di passi il motore stepper.";
Blockly.Msg.ARD_STEPPER_TWO_PINS = "2";
Blockly.Msg.ARD_TIME_DELAY = "attendi";
Blockly.Msg.ARD_TIME_DELAY_MICROS = "microsecondi";
Blockly.Msg.ARD_TIME_DELAY_MICRO_TIP = "Attendi per uno specifico intervallo di tempo in microsecondi";
Blockly.Msg.ARD_TIME_DELAY_TIP = "Aspetta per un intervallo di tempo in millisecondi";
Blockly.Msg.ARD_TIME_INF = "attendi per sempre (fine del programma)";
Blockly.Msg.ARD_TIME_INF_TIP = "Attende per un tempo infinito, cioè il programma termina.";
Blockly.Msg.ARD_TIME_MICROS = "Tempo passato in questo momento (microsecondi)";
Blockly.Msg.ARD_TIME_MICROS_TIP = "Restituisce il numero di millisecondi da quando la scheda Arduino ha iniziato a eseguire il programma. Deve essere salvato in una variabile positiva di tipo long integer";
Blockly.Msg.ARD_TIME_MILLIS = "Tempo passato in questo momento (millisecondi)";
Blockly.Msg.ARD_TIME_MILLIS_TIP = "Restituisce il numero di millisecondi da quando la scheda Arduino ha iniziato a eseguire il programma. Deve essere salvato in una variabile positiva di tipo long integer";
Blockly.Msg.ARD_TIME_MS = "millisecondi";
Blockly.Msg.ARD_TONEFREQ = "alla frequenza di";
Blockly.Msg.ARD_TONE_FREQ = "frequenza";
Blockly.Msg.ARD_TONE_PIN = "Tono su PIN#";
Blockly.Msg.ARD_TONE_PIN_TIP = "Genera dei toni audio su un pin.";
Blockly.Msg.ARD_TONE_TIP = "Imposta un tono sul pin alla frequenza specificata in un intervallo fra 31 e 65535";
Blockly.Msg.ARD_TONE_WARNING = "La frequenza dev'essere compresa fra 31 e 65535";
Blockly.Msg.ARD_TYPE_ARRAY = "Array";
Blockly.Msg.ARD_TYPE_BOOL = "Booleano";
Blockly.Msg.ARD_TYPE_CHAR = "Carattere";
Blockly.Msg.ARD_TYPE_CHILDBLOCKMISSING = "Dipendenza mancante";
Blockly.Msg.ARD_TYPE_DECIMAL = "Decimale";
Blockly.Msg.ARD_TYPE_LONG = "Numero Lungo";
Blockly.Msg.ARD_TYPE_NULL = "Null";
Blockly.Msg.ARD_TYPE_NUMBER = "Numero";
Blockly.Msg.ARD_TYPE_SHORT = "Numero breve";
Blockly.Msg.ARD_TYPE_TEXT = "Testo";
Blockly.Msg.ARD_TYPE_UNDEF = "Non definito";
Blockly.Msg.ARD_VAR_AS = "come";
Blockly.Msg.ARD_VAR_AS_TIP = "Imposta un tipo di valore";
Blockly.Msg.ARD_WRITE_TO = "a";
Blockly.Msg.NEW_INSTANCE = "Nuova istanza...";
Blockly.Msg.NEW_INSTANCE_TITLE = "Nuovo nome dell'istanza:";
Blockly.Msg.RENAME_INSTANCE = "Rinomina istanza...";
Blockly.Msg.RENAME_INSTANCE_TITLE = "Rinomina tutte le '%1' istanze a:";
